apiVersion: 1

datasources:
  - name: Holodeck Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: mydb
    user: user
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1400
    isDefault: true
    editable: true
